export { ProductMainSection } from './ProductMainSection'
export { ProductSideSection } from './ProductSideSection'
export { ProductReviewSection } from './ProductReviewSection'
export { ProductDescriptionSection } from './ProductDescriptionSection'
export type { DisplayProduct } from './ProductMainSection'
